technologies = {
    "Python": 0,
    "Rust": 0,
    "GO": 0,
    "TypeScript": 0,
    "JavaScript": 0,
    "Git": 0,
    "SQL": 0,
    "NoSQL": 0,
    "FastAPI": 0,
    "Django": 0,
    "Flask": 0,
    "Pyramid": 0,
    "Data Science": 0,
    "Data Analytics": 0,
    "Docker": 0,
    "Kubernetes": 0,
    "Json": 0,
    "XML": 0,
    "Yaml": 0,
    "REST API": 0,
    "REST": 0,
    "GraphQL": 0,
    "DRF": 0,
    "SSL": 0,
    "HTTP": 0,
    "MQTT": 0,
    "Pandas": 0,
    "SQLAlchemy": 0,
    "Pydantic": 0,
    "NumPy": 0,
    "Matplotlib": 0,
    "Seaborn": 0,
    "Beautiful Soup": 0,
    "Twisted Python": 0,
    "asyncio": 0,
    "API": 0,
    "AWS": 0,
    "linux": 0,
    "PostgresSQL": 0,
    "algorithms": 0,
    "CSS": 0,
    "HTML": 0,
    "MongoDB": 0,
    "fullstack": 0,
    "OOP": 0,
    "React": 0,
    "JS": 0,
    "Celery": 0,
    "Redis": 0,
    "Tableau": 0,
}
